name: industria
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  cupertino_icons: ^1.0.2

  #firebase
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.2
  firebase_storage: ^11.2.0
  firebase_auth: ^4.10.1

  #packages
  get_it: ^7.2.0
  watcher: ^1.1.0
  shared_preferences: ^2.2.1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  freezed: ^2.3.2
  json_annotation: ^4.8.1
  go_router: ^10.1.2
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  youtube_player_iframe: ^4.0.4
  intl: any
  float_column: ^2.1.1
  algolia: ^1.1.2
  flutter_svg: ^2.0.7
  vph_web_date_picker: ^0.0.4
  file_picker: ^5.5.0
  freezed_annotation: ^2.4.1
  bloc_concurrency: ^0.2.2
  styled_text: ^8.1.0
  dio: ^5.3.3
  adaptive_dialog: ^1.9.0+2
  pdf: ^3.10.4
  url_launcher: ^6.1.14
  mime_type: ^1.0.0
  video_player: ^2.8.1
  flutter_native_splash: ^2.3.5

  pandas_tableview:
    git:
      url: https://github.com/PandasCodi/pandas_tableview.git

#flutter_native_splash:
#  image: "assets/images/logo_big.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.4.6


flutter:


  uses-material-design: true
  generate: true

  assets:
     - assets/images/
     - assets/icons/
     - assets/videos/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
